### ISSUE TITLE
Types generation break generic types

### ISSUE THREAD

**Issue by prc5** [ExpediaGroup/cypress-codegen#115]
Hey! Great job with the codegen. I found one issue related to it.

Version: Cypress 11
Library version: latest
Macbook

Given I have custom command with generic type passed to it, types generation is breaking my code.

Example:

```ts
cy.get<AccountsListResponse>('@getAccountByCompany')
   .then((response) => {
       // some simple code inside
    })
    .as('account');

```

Output:

```ts
 cy.get <
 AccountsListResponse >
 '@getAccountByCompany'
 .then((response) => {
      // some simple code inside
 })
 .as('account')
```

To be honest it's quite easy to reproduce with generic types.

**Comment by danadajian** [comment]
@prc5 This should be fixed in v1.4.2. Thanks for pointing this out!
